### ISSUE TITLE
MELODIES Issue List

### ISSUE THREAD

**Issue by dwfncar** [NCAR/melodies#3]
- [ ] Add vertical model interpolation for upper air spatial plots https://github.com/NOAA-CSL/MELODIES-MONET/issues/242
- [ ] Add new MELODIES time vs height surface site plot type https://github.com/NOAA-CSL/MELODIES-MONET/issues/241
- [ ] Add new MELODIES spatial forecast data plot type https://github.com/NOAA-CSL/MELODIES-MONET/issues/240
- [ ] Add new MELODIES satellite swath plot type https://github.com/NOAA-CSL/MELODIES-MONET/issues/239
- [ ] Unify satellite swath data methods https://github.com/NOAA-CSL/MELODIES-MONET/issues/220
- [ ] Update satellite code documentation prior to initial pull to main https://github.com/NOAA-CSL/MELODIES-MONET/issues/139
